// 프론트 UI 프로토타입용 mock 데이터. 실제 API 연결 전까지만 사용.
// (CLAUDE.md §3 구조의 lib/mock.ts와 같은 성격 — "A가 초반에 사용")

import type { HospitalCareInfo } from './careTypes';

export const MOCK_USER_LOCATION = {
  lat: 36.0074,
  lng: 127.6606,
  label: '전북특별자치도 무주군',
};

export const MOCK_CARE_HOSPITALS: HospitalCareInfo[] = [
  {
    id: 'care-1',
    name: '무주 A의원',
    latitude: 36.0068,
    longitude: 127.6608,
    region: '전북특별자치도 무주군',
    address: '전북특별자치도 무주군 무주읍 한풍루로 3',
    travelTime: 8,
    distance: 5.2,
    grade: 'FAST',
    delay: 1.0,
    isOpen: true,
    closeTime: '18:30',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: false,
    isNightClinic: false,
    isHolidayClinic: false,
    recommendationReason: null,
  },
  {
    id: 'care-2',
    name: '무주 튼튼의원',
    latitude: 36.01,
    longitude: 127.665,
    region: '전북특별자치도 무주군',
    address: '전북특별자치도 무주군 무주읍 대차로 12',
    travelTime: 15,
    distance: 8,
    grade: 'FAST',
    delay: 1.1,
    isOpen: false,
    closeTime: '18:00',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: false,
    isNightClinic: false,
    isHolidayClinic: false,
    recommendationReason: null,
  },
  {
    id: 'care-3',
    name: '진안 건강의원',
    latitude: 35.7917,
    longitude: 127.4247,
    region: '전북특별자치도 진안군',
    address: '전북특별자치도 진안군 진안읍 군상리 12',
    travelTime: 27,
    distance: 20,
    grade: 'FAST',
    delay: 1.1,
    isOpen: true,
    closeTime: '19:00',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: false,
    isNightClinic: false,
    isHolidayClinic: false,
    recommendationReason: null,
  },
  {
    id: 'care-4',
    name: '대전 B어린이병원',
    latitude: 36.3504,
    longitude: 127.3845,
    region: '대전광역시',
    address: '대전광역시 서구 둔산로 123',
    travelTime: 37,
    distance: 41,
    grade: 'NORMAL',
    delay: 1.3,
    isOpen: true,
    closeTime: '22:00',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: true,
    isNightClinic: true,
    isHolidayClinic: false,
    recommendationReason: '현재 위치에서 가장 빠르게 소아 전문진료를 받을 수 있는 병원입니다.',
  },
  {
    id: 'care-5',
    name: '금산 C소아청소년과',
    latitude: 36.1088,
    longitude: 127.488,
    region: '충청남도 금산군',
    address: '충청남도 금산군 금산읍 중도리 45',
    travelTime: 42,
    distance: 39,
    grade: 'NORMAL',
    delay: 1.4,
    isOpen: true,
    closeTime: '21:00',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: true,
    isNightClinic: false,
    isHolidayClinic: false,
    recommendationReason: null,
  },
  {
    id: 'care-6',
    name: '함양 튼튼소아청소년과',
    latitude: 35.5203,
    longitude: 127.7255,
    region: '경상남도 함양군',
    address: '경상남도 함양군 함양읍 필봉산로 12',
    travelTime: 55,
    distance: 51,
    grade: 'SLOW',
    delay: 1.6,
    isOpen: true,
    closeTime: '18:00',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: true,
    isNightClinic: false,
    isHolidayClinic: false,
    recommendationReason: null,
  },
  {
    id: 'care-7',
    name: '전주 D어린이병원',
    latitude: 35.8242,
    longitude: 127.148,
    region: '전북특별자치도 전주시',
    address: '전북특별자치도 전주시 완산구 효자로 88',
    travelTime: 61,
    distance: 65,
    grade: 'SLOW',
    delay: 1.7,
    isOpen: true,
    closeTime: '20:00',
    acceptsPediatricPatients: true,
    hasPediatricSpecialist: true,
    isNightClinic: false,
    isHolidayClinic: true,
    recommendationReason: null,
  },
];
